config/routes.rb
MovieList::Application.routes.draw do
  
  match 'logout', to: 'sessions#destroy', via: 'get'
  match 'login', to: 'sessions#new', via: 'get'
  match 'signup', to: 'users#new', via: 'get'
  match 'userpage', to: 'sessions#userpage', via: 'get'
  match 'newpost', to: 'posts#new', via: 'get'

  resources :sessions, only: [:new, :destroy, :create]
  resources :users
  resources :movies, only: [:create, :show, :edit, :update]

  root to: 'landing_pages#home'
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings


  	def tag_list
	  self.tags.collect do |tag|
	    tag.name
	  end.join(", ")
	end

	 def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :movies, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :movies
	has_many :tags, through: :movies
    
    attr_accessor :password
	before_save :encrypt_password
	before_create { generate_token(:auth_token)}

	validates :password, presence:true, confirmation: true
	validates :email, presence: true, length: {maximum: 50}, uniqueness: true





  def self.authenticate(email, password)
		user = User.find_by_email(email)
		#if user exists and the password matches encrypted pw then return the user
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user 
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    helper_method :current_user


  private 

  	def current_user
  		@current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  	end

  	def signed_in?
     !current_user.nil?
    end

     def signed_in_user
      unless signed_in?
        flash[:notice] = "Please sign in."
        redirect_to root_url
      end
    end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  
  def home
  	@movie = Movie.new
  	@movies = current_user.movies if signed_in?
  	@tags = current_user.tags if signed_in?
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def create
		@movie = Movie.new(movies_params)
		@movie.user_id = current_user.id
		@movie.save

        redirect_to root_path
	end

	def show
		@movie = Movie.find(params[:id])
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	 def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movies_params)
      # Handle a successful update.
      flash[:success] = "d"
      redirect_to root_url
    end
  end



	private 
	  def movies_params
	  	params.require(:movie).permit(:name, :tag_list)
	  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user # means if user exists
  		cookies.permanent[:auth_token] = user.auth_token #used to track current user
  		flash[:success] = "You have logged in"
  		redirect_to root_url
  	else
  		flash.now.alert = "Log in failed!"
  		render 'new'
  	end
  end

  def destroy
  	cookies.delete :auth_token
    current_user = nil
  	flash[:success] = "You have Logged out!"
  	redirect_to root_path
  end

  private
    def session_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(users_params)
  	@user.save
  	redirect_to root_path
  end

  def index
  	@users = User.all
  end

  def show
    @user = User.find(current_user)
    @movie = Movie.new
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to root_path
  end

    private
      def users_params
      	params.require(:user).permit(:email, :username, :password, :password_confirmation)
      end


end

app/helpers/application_helper.rb
module ApplicationHelper

	
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/landing_pages/home.html.erb
<div id= "center"> 
<% if current_user %>
  <%= link_to 'logout', logout_path %></br>
  <%= link_to 'user profile', user_path(current_user) %>
  <%= render 'movies/form' %>
  <h1> Movie List </h1>
  <%= render @movies %>
<%else%>
<p> Welcome! </p>
  <%= link_to 'create user', new_user_path %>
  <%= link_to 'login', login_path %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
<%= key %>  <%= value %>
<% end %></br>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<h1> New Movie</h1>

<%= form_for (@movie) do |f| %>
	<% if @movie.errors.any? %>
	<div class= "error_messages">
		<h2>Form is Invalid </h2>
		<ul>
			<% for message in @movie.errors.full_messages %>
			<li> <%= message %> </li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %><br/>
	</p>
	<p>
        <%= f.label :tag_list %><br />
        <%= f.text_field :tag_list %>
   </p>

	<p class="button"> <%= f.submit "Post" %></p>
	<% end %>

app/views/movies/_movie.html.erb
<%= movie.name %> : <%= link_to 'show tags', movie_path(movie) %> : <%= link_to 'Update_Tag', edit_movie_path(movie) %></br>

app/views/movies/edit.html.erb
<h1> </h1>

<%= form_for [@movie] do |f| %>
	<% if @movie.errors.any? %>
	<div class= "error_messages">
		<h2>Form is Invalid </h2>
		<ul>
			<% for message in @movie.errors.full_messages %>
			<li> <%= message %> </li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<p>
        <%= f.label :tag_list %><br />
        <%= f.text_field :tag_list %>
   </p>

	<p class="button"> <%= f.submit "Post" %></p>
	<% end %>

app/views/movies/show.html.erb
<%= @movie.name %> 
<p> Tags:
<% @movie.tags.each do |t| %>
	<%= t.name %>
<% end %>
</p>

app/views/users/_user.html.erb
<%= user.username %>
<%= user.auth_token %>
<%= link_to 'back', root_path %>
<%= link_to 'user', user_path(current_user) %>

app/views/users/index.html.erb
<%= render @users %>

app/views/users/new.html.erb
<h1>New User Form</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class= "error_messages">
		<h2>Form is Invalid </h2>
		<ul>
			<% for message in @user.errors.full_messages %>
			<li> <%= message %> </li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<p>
		<%= f.label :email %><br/>
		<%= f.text_field :email %><br/>
	</p>
	<p>
		<%= f.label :username %><br/>
		<%= f.text_field :username %>
	</p>
	<p>
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</p>
		<p>
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</p>
	<p> <%= f.submit "Sign Up" %></p>
	<% end %>

app/views/users/show.html.erb
<%= render 'movies/form' %>